### PR TITLE
Eran/mgmt 1161

### PR DESCRIPTION
**Pull request by eranco74**
The release workflow was added in another PR: https://github.com/oshercc/ignition-manifests-and-kubeconfig-generate/pull/7
This changes are relevant for this ticket: https://issues.redhat.com/browse/MGMT-1163

### CODE REVIEW

**Review by yevgeny-shnaidman — COMMENTED** [review]
Why did you remove Dockerfile.installer-image? Did you move it to a different repository?

**Comment by eranco74** [comment]
> Why did you remove Dockerfile.installer-image? Did you move it to a different repository?

It can't be built in this repository.

**Comment by yevgeny-shnaidman** [comment]
until we insert our changes into openshift-installer, we need to be able to push this container somewhere. Let's leave it here , it should not interfere with the building of ignition-kubeconfig

**Comment by eranco74** [comment]
> until we insert our changes into openshift-installer, we need to be able to push this container somewhere. Let's leave it here , it should not interfere with the building of ignition-kubeconfig

I think it belongs to the fork you have in the openshift installer where it can be built.

**Comment by eranco74** [comment]
Tested full installation - works

**Pull request closed without merging**
